# Generated by Django 2.0.8 on 2018-09-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_hotornot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='questionmultiple',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='questionopen',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='questionyesorno',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
    ]
