# Generated by Django 2.0.8 on 2018-09-11 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_hotornot', '0002_auto_20180910_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmultiple',
            name='question_type',
            field=models.CharField(default='Multiple-Choice', max_length=50),
        ),
        migrations.AddField(
            model_name='questionopen',
            name='question_type',
            field=models.CharField(default='Open / Written answer', max_length=50),
        ),
        migrations.AddField(
            model_name='questionyesorno',
            name='question_type',
            field=models.CharField(default='Yes - No', max_length=50),
        ),
    ]
