# Generated by Django 2.0.8 on 2018-09-06 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_hotornot', '0002_auto_20180906_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useransweropen',
            old_name='answer_note',
            new_name='answer_text',
        ),
        migrations.RemoveField(
            model_name='useranswermultiple',
            name='answer_note',
        ),
        migrations.RemoveField(
            model_name='useranswermultiple',
            name='answer_value',
        ),
        migrations.RemoveField(
            model_name='useransweropen',
            name='answer_value',
        ),
    ]
