# Generated by Django 2.0.8 on 2018-09-06 22:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_hotornot', '0003_auto_20180906_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionmultiple',
            name='options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=150), null=True, size=None),
        ),
    ]
