# Generated by Django 2.0.8 on 2018-09-06 22:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_hotornot', '0004_questionmultiple_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmultiple',
            name='options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=150), default=list, null=True, size=4),
        ),
    ]
