# Generated by Django 2.0.8 on 2018-09-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='push_notifications',
            field=models.BooleanField(default=True, verbose_name='Push notfications enabled'),
        ),
        migrations.AddField(
            model_name='user',
            name='reg_code',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='Registration Code'),
        ),
    ]
